export default {
    routes: {
        home: 'Home',
        settings: 'Settings',
        order: 'Order',
        delete: 'Delete',
        create: 'Create',
        edit: 'Edit',
        display: 'Display'
    },
    keys: {
        settings: 'USER_SETTINGS',
        projPrefix: 'PROJ-',
    },
    languages: ['English', 'Español',],
    dateFormats: ['MM/DD', 'DD/MM', 'MM-DD', 'DD-MM', 'YY/MM/DD', 'DD/MM/YY', 'MM/DD/YY', 'YY-MM-DD', 'DD-MM-YY', 'MM-DD-YY'],
    timeFormat: 'h:mm a',
    English: {
        buttons: {
            home: 'Home',
            settings: 'Settings',
            order: 'Order',
            save: 'Save',
            delete: 'Delete',
            create: 'New',
            edit: 'Edit',
            cancel: 'Cancel',
            done: 'Done',
            okay: 'Okay',
            setToDefault: 'Set to Default',
            allSettings: {
                darkMode: 'Dark Mode On/Off',
                language: 'Language',
                dateFormat: 'Date Format:   ',
                notifications: 'Default Notification Preferences',
                freq: 'Notification Frequency:   ',
                time: 'Notification Time:   ', 
                unit: 'Set Default Unit:   ',
                editUnit: 'Edit or Add Unit Names',
                tags: 'Edit Your Tags',
                deleteAll: 'Start Fresh - Delete All Projects',
                feedback: 'Send Us Your Feedback'
            }
        },
        labels: {
            title: 'Project Title: ',
            dueDate: 'Project Due Date: ',
            startDate: 'Project Start Date: ',
            unitName: 'Unit Name: ',
            startUnit: 'First unit: ',
            currentUnit: 'Current unit: ', 
            endUnit: 'Last unit: ', 
            total: 'Total ',
            tags: 'Tags, e.g. class or genre (optional): ',
            tagsDisplay: 'Tags: ',
            notification: 'Notifications: ',
            frequency: 'Freq:',
            time: '  Time:',
            perDay: 'Complete num unit freq',
            complete: 'This project is completed',
            dueToday: 'This project is due today',
            overDue: 'This project is OVERDUE',
            new: 'NEW',
        },
        placeholder: {
            title: 'Title of your project...',
            tags: 'Chemistry, English, Nonfiction, Sci-Fi...',
            noTags: 'no tags...',
            loading: 'Loading...'
        },
        units: ['word', 'page', 'chapter'],
        unitPlurals: ['words', 'pages', 'chapters'],
        frequencyWords: ['default', 'daily', 'every 2 days', 'every 3 days', 'every 4 days', 'every 5 days', 'every 6 days', 'weekly'],
        orders: ['Title', 'Due Next'],
        alerts: {
            title: {
                exists: 'Title already exists',
                blank: 'Title cannot be blank'
            },
            first: 'First unit cannot be blank',
            last: 'Last unit cannot be blank',
            firstSmaller: 'Last unit cannot be a smaller number than first unit',
            charTitle: 'Title can only contain letters, numbers, spaces, apostrophes, dashes and underscores.',
            charTags: 'Tags can only contain letters, numbers, spaces, apostrophes, dashes and underscores. Use commas to separate.',
            confirmDelete: 'Are you sure you want to delete this project?',
            order: 'Select below to reorder your projects:',
            create_edit: {
                unit: 'Choose a unit below. You can add your own units in Settings.',
                time: 'Choose a time of day to be notified. You can edit the default time in Settings.',
                freq: 'Choose how often to receive notifications. You can edit the default frequency in Settings.'
            },
            settings: {
                language: 'Please select a language below. \n We would love to add more languages. If you would like to translate, please use the Feedback button to send us an email.',
                dateFormat: 'Please select a date format below:',
                notify: 'These notification settings are used by all projects set to default. Select a frequency below:',
                defUnit: 'Choose a default unit for your projects:',
                editUnit:'',
                deleteAll: 'Are you sure you want to delete all of your projects? This cannot be undone.',
            }
        },
    },
    Español: {
        buttons: {
            home: 'Home',
            settings: 'Settings',
            order: 'Order',
            save: 'Save',
            delete: 'Delete',
            create: 'New',
            edit: 'Edit',
            cancel: 'Cancel',
            done: 'Done',
            okay: 'Okay',
            setToDefault: 'Default Notifications',
            allSettings: {
                darkMode: 'Dark Mode On/Off',
                language: 'Idioma',
                dateFormat: 'Date Format',
                notifications: 'Default Notification Preferences',
                unit: 'Set Default Unit',
                editUnit: 'Edit or Add Unit Names',
                tags: 'Edit Your Tags',
                deleteAll: 'Start Fresh - Delete All Projects',
                feedback: 'Send Us Your Feedback'
            }
        },
        labels: {
            title: 'Project Title: ',
            dueDate: 'Project Due Date: ',
            startDate: 'Project Start Date: ',
            unitName: 'Unit Name: ',
            startUnit: 'First unit: ',
            currentUnit: 'Current unit: ', 
            endUnit: 'Last unit: ', 
            total: 'Total ',
            tags: 'Tags, e.g. class or genre (optional): ',
            tagsDisplay: 'Tags: ',
            notification: 'Notifications: ',
            frequency: 'Freq:',
            time: '  Time:',
            perDay: 'Complete num unit(s) freq',
            complete: 'This project is completed',
            dueToday: 'This project is due today',
            overDue: 'This project is OVERDUE',
        },
        placeholder: {
            title: 'Title of your project...',
            tags: 'Chemistry, English, Nonfiction, Sci-Fi...',
            noTags: 'no tags...',
            loading: 'Loading...'
        },
        units: ['palabra', 'página', 'capítulo'],
        unitPlurals: ['palabras', 'páginas', 'capítulos'],
        frequencyWords: ['default', 'daily', 'every 2 days', 'every 3 days', 'every 4 days', 'every 5 days', 'every 6 days', 'weekly'],
        alerts: {
            title: {
                exists: 'Title already exists',
                blank: 'Title cannot be blank'
            },
            first: 'First unit cannot be blank',
            last: 'Last unit cannot be blank',
            firstSmaller: 'Last unit cannot be a smaller number than first unit',
            charTitle: 'Title can only contain letters, numbers, spaces, apostrophes, dashes and underscores.',
            charTags: 'Tags can only contain letters, numbers, spaces, apostrophes, dashes and underscores. Use commas to separate.',
            confirmDelete: 'Are you sure you want to delete this project?',
            settings: {
                language: 'Please select a language below. \n We would love to add more languages. If you would like to translate, please use the Feedback button to send us an email.',
                dateFormat: 'Please select a date format below:',
                notify: '',
                unit: '',
                deleteAll: 'Are you sure you want to delete all of your projects? This cannot be undone.',
            }
        },
    },
};